#!/usr/bin/env python3
import os
import sys
from pathlib import Path


def bootstrap():
    sys.path.insert(0, str(Path(__file__).resolve().parent / "src"))

    import setup

    setup.init()

    from harness import MainWrapper
    from main import main

    MainWrapper(main)


if __name__ == "__main__":
    bootstrap()
