version: 2
jobs:
  build:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - run:
          name: setup venv
          command: |
            cd src
            make test
